### ISSUE TITLE
Question: Can this be used to control Hue lights with Apple TV

### ISSUE THREAD

**Issue by steven596** [NorthernMan54/homebridge-cmd-television#3]
How would I configure this plugin to turn on/off my hue lights when I turn my Apple TV on/off? Is that possible or am I misunderstanding what the purpose of this plugin is.

Thanks for the help

**Comment by NorthernMan54** [comment]
My main use case for this was control of my Apple TV from my Alexa and the homebridge-Alexa plugin, as homebridge-appletv-remote stopped working due to recent tvOS changes.  Technically it could be used to trigger an HomeKit automation like turn on my hue lights when the tv is on, but that portion of code that detects the tv status isn’t very robust, and is likely very laggy or just plain not working well.

So give it a try, and see how it works, but if it doesn’t work well, it is unlikely to be fixed, unless someone can figure out the issue and submit a pull request.
